"""
Material Database - Real material properties for base materials
"""
from dataclasses import dataclass
from typing import Dict, List, Optional
import json


@dataclass
class MaterialProperties:
    """Real physical properties of a material"""
    name: str
    formula: str
    density: float  # g/cm³
    youngs_modulus: float  # GPa
    tensile_strength: float  # MPa
    thermal_conductivity: float  # W/m·K
    band_gap: float  # eV
    crystal_structure: str
    lattice_constants: Dict[str, float]  # a, b, c in Å
    space_group: str
    poisson_ratio: float
    hardness: float  # GPa
    melting_point: float  # K
    thermal_expansion: float  # 1/K
    electrical_conductivity: float  # S/m
    gluon_mass: float  # From lattice_forge
    formation_energy: float  # eV/atom
    oloid_closure: bool
    production_key: str = ""  # Key for production method lookup


# Pre-loaded database of real materials
MATERIAL_DATABASE: Dict[str, MaterialProperties] = {
    # ─── ORIGINAL 8 MATERIALS ───
    "graphene": MaterialProperties(
        name="Graphene",
        formula="C",
        density=2.267,
        youngs_modulus=1000.0,
        tensile_strength=130000.0,
        thermal_conductivity=5300.0,
        band_gap=0.0,
        crystal_structure="Hexagonal",
        lattice_constants={"a": 2.461, "b": 2.461, "c": 6.708},
        space_group="P6/mmm",
        poisson_ratio=0.165,
        hardness=0.0,
        melting_point=4000.0,
        thermal_expansion=-8e-6,
        electrical_conductivity=1e8,
        gluon_mass=0.98,
        formation_energy=0.0,
        oloid_closure=True,
        production_key="graphene",
    ),
    "mos2": MaterialProperties(
        name="Molybdenum Disulfide",
        formula="MoS₂",
        density=5.06,
        youngs_modulus=270.0,
        tensile_strength=15000.0,
        thermal_conductivity=52.0,
        band_gap=1.8,
        crystal_structure="Hexagonal",
        lattice_constants={"a": 3.16, "b": 3.16, "c": 12.3},
        space_group="P6₃/mmc",
        poisson_ratio=0.25,
        hardness=1.5,
        melting_point=1450.0,
        thermal_expansion=6.5e-6,
        electrical_conductivity=1e-3,
        gluon_mass=1.02,
        formation_energy=-1.2,
        oloid_closure=True,
        production_key="mos2",
    ),
    "bp": MaterialProperties(
        name="Black Phosphorus",
        formula="P",
        density=2.69,
        youngs_modulus=45.0,
        tensile_strength=1000.0,
        thermal_conductivity=40.0,
        band_gap=0.3,
        crystal_structure="Orthorhombic",
        lattice_constants={"a": 3.31, "b": 4.38, "c": 10.48},
        space_group="Cmca",
        poisson_ratio=0.3,
        hardness=0.5,
        melting_point=873.0,
        thermal_expansion=10e-6,
        electrical_conductivity=100.0,
        gluon_mass=1.15,
        formation_energy=-0.08,
        oloid_closure=True,
        production_key="bp",
    ),
    "hbn": MaterialProperties(
        name="Hexagonal Boron Nitride",
        formula="BN",
        density=2.29,
        youngs_modulus=850.0,
        tensile_strength=33000.0,
        thermal_conductivity=400.0,
        band_gap=6.0,
        crystal_structure="Hexagonal",
        lattice_constants={"a": 2.504, "b": 2.504, "c": 6.66},
        space_group="P6₃/mmc",
        poisson_ratio=0.21,
        hardness=15.0,
        melting_point=3273.0,
        thermal_expansion=2.5e-6,
        electrical_conductivity=1e-12,
        gluon_mass=0.87,
        formation_energy=-0.5,
        oloid_closure=True,
        production_key="hbn",
    ),
    "mowse2": MaterialProperties(
        name="MoWSe₂ Alloy",
        formula="Mo₀.₅W₀.₅Se₂",
        density=7.2,
        youngs_modulus=200.0,
        tensile_strength=12000.0,
        thermal_conductivity=35.0,
        band_gap=1.4,
        crystal_structure="Hexagonal",
        lattice_constants={"a": 3.22, "b": 3.22, "c": 12.9},
        space_group="P6₃/mmc",
        poisson_ratio=0.28,
        hardness=2.0,
        melting_point=1500.0,
        thermal_expansion=7e-6,
        electrical_conductivity=1e-2,
        gluon_mass=1.33,
        formation_energy=-0.8,
        oloid_closure=False,
        production_key="mowse2",
    ),
    "mxene": MaterialProperties(
        name="MXene (Ti₃C₂Tₓ)",
        formula="Ti₃C₂(OH)₂",
        density=4.2,
        youngs_modulus=300.0,
        tensile_strength=8000.0,
        thermal_conductivity=150.0,
        band_gap=0.0,
        crystal_structure="Hexagonal",
        lattice_constants={"a": 3.04, "b": 3.04, "c": 20.0},
        space_group="P-3m1",
        poisson_ratio=0.22,
        hardness=5.0,
        melting_point=2000.0,
        thermal_expansion=8e-6,
        electrical_conductivity=1e6,
        gluon_mass=1.41,
        formation_energy=-1.5,
        oloid_closure=False,
        production_key="mxene",
    ),
    "sto": MaterialProperties(
        name="Strontium Titanate",
        formula="SrTiO₃",
        density=5.12,
        youngs_modulus=267.0,
        tensile_strength=400.0,
        thermal_conductivity=12.0,
        band_gap=3.2,
        crystal_structure="Cubic",
        lattice_constants={"a": 3.905, "b": 3.905, "c": 3.905},
        space_group="Pm-3m",
        poisson_ratio=0.25,
        hardness=6.5,
        melting_point=2353.0,
        thermal_expansion=10e-6,
        electrical_conductivity=1e-8,
        gluon_mass=1.28,
        formation_energy=-2.1,
        oloid_closure=True,
        production_key="sto",
    ),
    "tbg": MaterialProperties(
        name="Twisted Bilayer Graphene @ 1.1°",
        formula="C",
        density=2.267,
        youngs_modulus=950.0,
        tensile_strength=120000.0,
        thermal_conductivity=5000.0,
        band_gap=0.0,
        crystal_structure="Moiré superlattice",
        lattice_constants={"a": 134.0, "b": 134.0, "c": 6.7},
        space_group="P1",
        poisson_ratio=0.15,
        hardness=0.0,
        melting_point=4000.0,
        thermal_expansion=-7e-6,
        electrical_conductivity=1e7,
        gluon_mass=2.04,
        formation_energy=0.02,
        oloid_closure=True,
        production_key="tbg",
    ),

    # ─── NEW: 2D TMD FAMILY ───
    "ws2": MaterialProperties(
        name="Tungsten Disulfide",
        formula="WS₂",
        density=7.5,
        youngs_modulus=270.0,
        tensile_strength=15000.0,
        thermal_conductivity=60.0,
        band_gap=2.0,
        crystal_structure="Hexagonal",
        lattice_constants={"a": 3.15, "b": 3.15, "c": 12.3},
        space_group="P6₃/mmc",
        poisson_ratio=0.22,
        hardness=3.0,
        melting_point=1500.0,
        thermal_expansion=5.5e-6,
        electrical_conductivity=1e-4,
        gluon_mass=1.05,
        formation_energy=-1.3,
        oloid_closure=True,
        production_key="ws2",
    ),
    "wse2": MaterialProperties(
        name="Tungsten Diselenide",
        formula="WSe₂",
        density=9.3,
        youngs_modulus=160.0,
        tensile_strength=10000.0,
        thermal_conductivity=40.0,
        band_gap=1.7,
        crystal_structure="Hexagonal",
        lattice_constants={"a": 3.28, "b": 3.28, "c": 12.9},
        space_group="P6₃/mmc",
        poisson_ratio=0.25,
        hardness=2.5,
        melting_point=1400.0,
        thermal_expansion=6.0e-6,
        electrical_conductivity=1e-3,
        gluon_mass=1.12,
        formation_energy=-1.0,
        oloid_closure=True,
        production_key="wse2",
    ),
    "mose2": MaterialProperties(
        name="Molybdenum Diselenide",
        formula="MoSe₂",
        density=6.9,
        youngs_modulus=180.0,
        tensile_strength=11000.0,
        thermal_conductivity=45.0,
        band_gap=1.5,
        crystal_structure="Hexagonal",
        lattice_constants={"a": 3.29, "b": 3.29, "c": 12.9},
        space_group="P6₃/mmc",
        poisson_ratio=0.26,
        hardness=2.0,
        melting_point=1400.0,
        thermal_expansion=6.2e-6,
        electrical_conductivity=1e-2,
        gluon_mass=1.08,
        formation_energy=-0.9,
        oloid_closure=True,
        production_key="mose2",
    ),

    # ─── NEW: HEXAGONAL LAYERED ───
    "inclse": MaterialProperties(
        name="Indium Selenium",
        formula="InSe",
        density=5.8,
        youngs_modulus=120.0,
        tensile_strength=8000.0,
        thermal_conductivity=30.0,
        band_gap=1.3,
        crystal_structure="Hexagonal",
        lattice_constants={"a": 4.00, "b": 4.00, "c": 16.0},
        space_group="P6₃/mmc",
        poisson_ratio=0.28,
        hardness=1.5,
        melting_point=1000.0,
        thermal_expansion=8e-6,
        electrical_conductivity=1e-1,
        gluon_mass=1.18,
        formation_energy=-0.6,
        oloid_closure=True,
        production_key="inclse",
    ),
    "gas": MaterialProperties(
        name="Gallium Sulfide",
        formula="GaS",
        density=3.8,
        youngs_modulus=150.0,
        tensile_strength=9000.0,
        thermal_conductivity=25.0,
        band_gap=2.5,
        crystal_structure="Hexagonal",
        lattice_constants={"a": 3.58, "b": 3.58, "c": 15.5},
        space_group="P6₃/mmc",
        poisson_ratio=0.24,
        hardness=2.0,
        melting_point=1200.0,
        thermal_expansion=7e-6,
        electrical_conductivity=1e-2,
        gluon_mass=1.15,
        formation_energy=-0.7,
        oloid_closure=True,
        production_key="gas",
    ),
    "gase": MaterialProperties(
        name="Gallium Selenide",
        formula="GaSe",
        density=5.1,
        youngs_modulus=100.0,
        tensile_strength=7000.0,
        thermal_conductivity=20.0,
        band_gap=2.1,
        crystal_structure="Hexagonal",
        lattice_constants={"a": 3.74, "b": 3.74, "c": 15.9},
        space_group="P6₃/mmc",
        poisson_ratio=0.26,
        hardness=1.8,
        melting_point=1100.0,
        thermal_expansion=8e-6,
        electrical_conductivity=1e-3,
        gluon_mass=1.20,
        formation_energy=-0.5,
        oloid_closure=True,
        production_key="gase",
    ),

    # ─── NEW: PEROVSKITE OXIDES ───
    "btio3": MaterialProperties(
        name="Barium Titanate",
        formula="BaTiO₃",
        density=6.0,
        youngs_modulus=180.0,
        tensile_strength=300.0,
        thermal_conductivity=11.0,
        band_gap=3.0,
        crystal_structure="Tetragonal",
        lattice_constants={"a": 3.99, "b": 3.99, "c": 4.04},
        space_group="P4mm",
        poisson_ratio=0.30,
        hardness=5.0,
        melting_point=1900.0,
        thermal_expansion=9e-6,
        electrical_conductivity=1e-10,
        gluon_mass=1.35,
        formation_energy=-2.5,
        oloid_closure=False,
        production_key="btio3",
    ),
    "pbtio3": MaterialProperties(
        name="Lead Titanate",
        formula="PbTiO₃",
        density=8.0,
        youngs_modulus=150.0,
        tensile_strength=250.0,
        thermal_conductivity=8.0,
        band_gap=2.8,
        crystal_structure="Tetragonal",
        lattice_constants={"a": 3.90, "b": 3.90, "c": 4.15},
        space_group="P4mm",
        poisson_ratio=0.32,
        hardness=4.5,
        melting_point=1800.0,
        thermal_expansion=10e-6,
        electrical_conductivity=1e-11,
        gluon_mass=1.42,
        formation_energy=-2.3,
        oloid_closure=False,
        production_key="pbtio3",
    ),
    "knbo3": MaterialProperties(
        name="Potassium Niobate",
        formula="KNbO₃",
        density=4.6,
        youngs_modulus=200.0,
        tensile_strength=350.0,
        thermal_conductivity=15.0,
        band_gap=3.2,
        crystal_structure="Orthorhombic",
        lattice_constants={"a": 3.99, "b": 5.69, "c": 3.97},
        space_group="Amm2",
        poisson_ratio=0.28,
        hardness=5.5,
        melting_point=1950.0,
        thermal_expansion=8e-6,
        electrical_conductivity=1e-9,
        gluon_mass=1.30,
        formation_energy=-2.0,
        oloid_closure=False,
        production_key="knbo3",
    ),

    # ─── NEW: 2D MONOELEMENTAL ───
    "stanene": MaterialProperties(
        name="Stanene",
        formula="Sn",
        density=5.7,
        youngs_modulus=80.0,
        tensile_strength=5000.0,
        thermal_conductivity=25.0,
        band_gap=0.1,
        crystal_structure="Hexagonal (buckled)",
        lattice_constants={"a": 2.80, "b": 2.80, "c": 7.0},
        space_group="P3m1",
        poisson_ratio=0.22,
        hardness=1.0,
        melting_point=800.0,
        thermal_expansion=12e-6,
        electrical_conductivity=1e5,
        gluon_mass=1.25,
        formation_energy=-0.2,
        oloid_closure=True,
        production_key="stanene",
    ),
    "germanene": MaterialProperties(
        name="Germanene",
        formula="Ge",
        density=4.2,
        youngs_modulus=100.0,
        tensile_strength=6000.0,
        thermal_conductivity=30.0,
        band_gap=0.05,
        crystal_structure="Hexagonal (buckled)",
        lattice_constants={"a": 2.45, "b": 2.45, "c": 6.5},
        space_group="P3m1",
        poisson_ratio=0.20,
        hardness=1.2,
        melting_point=1000.0,
        thermal_expansion=10e-6,
        electrical_conductivity=1e6,
        gluon_mass=1.10,
        formation_energy=-0.1,
        oloid_closure=True,
        production_key="germanene",
    ),
    "silicene": MaterialProperties(
        name="Silicene",
        formula="Si",
        density=2.3,
        youngs_modulus=95.0,
        tensile_strength=5500.0,
        thermal_conductivity=35.0,
        band_gap=0.02,
        crystal_structure="Hexagonal (buckled)",
        lattice_constants={"a": 2.28, "b": 2.28, "c": 6.0},
        space_group="P3m1",
        poisson_ratio=0.19,
        hardness=1.5,
        melting_point=1200.0,
        thermal_expansion=8e-6,
        electrical_conductivity=1e7,
        gluon_mass=1.00,
        formation_energy=0.0,
        oloid_closure=True,
        production_key="silicene",
    ),

    # ─── NEW: WIDE GAP INSULATORS ───
    "al2o3": MaterialProperties(
        name="Aluminum Oxide (Alumina)",
        formula="Al₂O₃",
        density=3.97,
        youngs_modulus=380.0,
        tensile_strength=400.0,
        thermal_conductivity=30.0,
        band_gap=8.8,
        crystal_structure="Trigonal",
        lattice_constants={"a": 4.76, "b": 4.76, "c": 12.99},
        space_group="R-3c",
        poisson_ratio=0.23,
        hardness=20.0,
        melting_point=2345.0,
        thermal_expansion=8.5e-6,
        electrical_conductivity=1e-14,
        gluon_mass=1.50,
        formation_energy=-4.0,
        oloid_closure=True,
        production_key="al2o3",
    ),
    "sio2_q": MaterialProperties(
        name="Quartz (α-SiO₂)",
        formula="SiO₂",
        density=2.65,
        youngs_modulus=95.0,
        tensile_strength=500.0,
        thermal_conductivity=12.0,
        band_gap=9.0,
        crystal_structure="Trigonal",
        lattice_constants={"a": 4.91, "b": 4.91, "c": 5.41},
        space_group="P3₂21",
        poisson_ratio=0.17,
        hardness=7.0,
        melting_point=1983.0,
        thermal_expansion=0.5e-6,
        electrical_conductivity=1e-16,
        gluon_mass=1.55,
        formation_energy=-4.5,
        oloid_closure=True,
        production_key="sio2_q",
    ),
    "mgo": MaterialProperties(
        name="Magnesium Oxide",
        formula="MgO",
        density=3.58,
        youngs_modulus=300.0,
        tensile_strength=300.0,
        thermal_conductivity=60.0,
        band_gap=7.8,
        crystal_structure="Cubic",
        lattice_constants={"a": 4.21, "b": 4.21, "c": 4.21},
        space_group="Fm-3m",
        poisson_ratio=0.19,
        hardness=15.0,
        melting_point=3125.0,
        thermal_expansion=13e-6,
        electrical_conductivity=1e-12,
        gluon_mass=1.45,
        formation_energy=-3.8,
        oloid_closure=True,
        production_key="mgo",
    ),
}


def get_material(name: str) -> Optional[MaterialProperties]:
    """Get material from database by name (case-insensitive)"""
    key = name.lower().replace(" ", "").replace("@", "").replace("°", "").replace(".", "")
    if key in MATERIAL_DATABASE:
        return MATERIAL_DATABASE[key]
    # Fuzzy match
    for k, v in MATERIAL_DATABASE.items():
        if name.lower() in v.name.lower() or v.name.lower() in name.lower():
            return v
    return None


def list_materials() -> List[str]:
    """List all available materials"""
    return [m.name for m in MATERIAL_DATABASE.values()]


def add_custom_material(props: MaterialProperties):
    """Add a custom material to the database"""
    key = props.name.lower().replace(" ", "").replace("@", "").replace("°", "").replace(".", "")
    if not props.production_key:
        props.production_key = key
    MATERIAL_DATABASE[key] = props