"""SolidWorks adapter for CADForge receipts.

This module deliberately does not replace SolidWorks. It emits a small VBA
macro module that a SolidWorks user can run/import to recreate the legal
CADForge wire skeleton as sketch geometry. SolidWorks remains the professional
modeling environment; CADForge/WireBlock supplies the pre-legalized template,
bounded variables, and receipt.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Iterable, Mapping
import json


def _design_from_payload(payload: Mapping[str, Any]) -> Dict[str, Any]:
    if "payload" in payload and isinstance(payload["payload"], Mapping):
        nested = payload["payload"]
        if isinstance(nested.get("design"), Mapping):
            return dict(nested["design"])
    if "design" in payload and isinstance(payload["design"], Mapping):
        return dict(payload["design"])
    if "nodes" in payload and "edges" in payload:
        return dict(payload)
    raise ValueError("expected a CADForge design or WireBlock receipt payload")


def _num(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except Exception:
        return default


def _vba_string(value: Any) -> str:
    return '"' + str(value).replace('"', '""') + '"'


def emit_solidworks_vba(
    design_or_receipt: Mapping[str, Any],
    *,
    macro_name: str = "CADForgeWireBlockImport",
    sketch_name: str = "CADForge_WireBlock_Skeleton",
    unit_scale_mm: float = 10.0,
) -> str:
    """Emit a SolidWorks VBA module for the CADForge wire skeleton.

    `unit_scale_mm` maps one CADForge template unit to millimeters. SolidWorks
    API coordinates are emitted in meters.
    """
    design = _design_from_payload(design_or_receipt)
    nodes = {n["id"]: n for n in design.get("nodes", [])}
    edges = list(design.get("edges", []))
    meter = unit_scale_mm / 1000.0

    lines = [
        "Option Explicit",
        "",
        "' Generated by CADForge / WireBlock.",
        "' SolidWorks remains the CAD system; this macro imports the legal wire skeleton.",
        "' Review dimensions, constraints, and manufacturing features in SolidWorks.",
        "",
        "Dim swApp As SldWorks.SldWorks",
        "Dim swModel As SldWorks.ModelDoc2",
        "Dim swSketchMgr As SldWorks.SketchManager",
        "",
        f"Sub {macro_name}()",
        "    Set swApp = Application.SldWorks",
        "    Set swModel = swApp.NewPart",
        "    If swModel Is Nothing Then",
        "        MsgBox \"CADForge import failed: could not create a new part.\"",
        "        Exit Sub",
        "    End If",
        "    Set swSketchMgr = swModel.SketchManager",
        "    swSketchMgr.Insert3DSketch True",
        f"    swModel.SetTitle2 {_vba_string(str(design.get('name', 'CADForge Design')))}",
        f"    Debug.Print \"CADForge family: {str(design.get('family', 'unknown'))}\"",
        f"    Debug.Print \"WireBlock design id: {str(design.get('design_id', 'unknown'))}\"",
        "",
    ]

    for edge in edges:
        source = nodes.get(edge.get("source"))
        target = nodes.get(edge.get("target"))
        if not source or not target:
            continue
        x1 = _num(source.get("x")) * meter
        y1 = _num(source.get("y")) * meter
        z1 = _num(source.get("z")) * meter
        x2 = _num(target.get("x")) * meter
        y2 = _num(target.get("y")) * meter
        z2 = _num(target.get("z")) * meter
        lines.append(
            "    swSketchMgr.CreateLine "
            f"{x1:.9f}, {y1:.9f}, {z1:.9f}, {x2:.9f}, {y2:.9f}, {z2:.9f}"
        )

    lines += [
        "",
        "    swSketchMgr.Insert3DSketch True",
        "    swModel.ForceRebuild3 False",
        "    MsgBox \"CADForge WireBlock skeleton imported. Apply SolidWorks dimensions/features next.\"",
        "End Sub",
        "",
    ]
    return "\n".join(lines)


def export_solidworks_adapter(
    design_or_receipt: Mapping[str, Any],
    out_path: str | Path,
    *,
    macro_name: str = "CADForgeWireBlockImport",
    sketch_name: str = "CADForge_WireBlock_Skeleton",
    unit_scale_mm: float = 10.0,
) -> str:
    """Write a `.bas` SolidWorks VBA adapter module and return its path."""
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    macro = emit_solidworks_vba(
        design_or_receipt,
        macro_name=macro_name,
        sketch_name=sketch_name,
        unit_scale_mm=unit_scale_mm,
    )
    out.write_text(macro, encoding="utf-8")
    return str(out)


def export_from_json(in_path: str | Path, out_path: str | Path, **kwargs: Any) -> str:
    """Read a CADForge design/receipt JSON and write a SolidWorks `.bas` macro."""
    payload = json.loads(Path(in_path).read_text(encoding="utf-8"))
    return export_solidworks_adapter(payload, out_path, **kwargs)


__all__ = [
    "emit_solidworks_vba",
    "export_solidworks_adapter",
    "export_from_json",
]
